# Generated by Django 5.0.3 on 2024-03-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nauli', '0002_alter_vehicle_bus_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='bus_class',
            field=models.CharField(choices=[('Odinary', 'Odinary'), ('Semi-luxury', 'Semi-luxury'), ('Luxury', 'Luxury')], default='Semi-luxury', max_length=15),
        ),
    ]
