# Generated by Django 5.0.3 on 2024-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nauli', '0003_alter_vehicle_bus_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
