# Generated by Django 5.0.3 on 2024-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nauli', '0004_vehicle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
